on:
 push:
   tags:
     - '!refs/tags/*'
   branches:
     - '*'
jobs:
 run_tests:
   runs-on: [ubuntu-latest]
steps:
  # Чекаутим код
 - uses: actions/checkout@master
   # Устанавливаем python нужной версии
 - uses: actions/setup-python@v1
   with:
     python-version: '3.12'
     architecture: 'x64'
 - name: Install requirements
   # Устанавливаем зависимости
   run: pip install uv && uv sync
 - name: Run tests
   run: coverage run test.py
 - name: Tests report
   run: coverage report