on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      # Чекаутим код
      - uses: actions/checkout@master

      # Устанавливаем python нужной версии
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          architecture: 'x64'

      # Устанавливаем зависимости
      - name: Install requirements
        run: |
          pip install uv
          uv sync

      # Запускаем тесты
      - name: Run tests
        run: |
          coverage run test.py

      # Генерируем отчет о тестах
      - name: Tests report
        run: |
          coverage report